import { Router } from "express";
import { ProductStatus } from "../../generated/prisma/enums.js";
import { HttpError } from "../../lib/http-error.js";
import { prisma } from "../../lib/prisma.js";
import { requireAuth, type AuthRequest } from "../auth/auth.middleware.js";
export const cartRouter = Router();
cartRouter.use(requireAuth);
const include = { items: { include: { product: { include: { images: { where: { isPrimary: true }, take: 1 } } }, productVariant: true } } } as const;
async function userCart(userId:string){const existing=await prisma.cart.findFirst({where:{userId},include});return existing??prisma.cart.create({data:{userId},include});}
cartRouter.get("/",async(req,res,next)=>{try{res.json({data:await userCart((req as AuthRequest).auth!.sub)});}catch(e){next(e);}});
cartRouter.post("/items",async(req,res,next)=>{try{const userId=(req as AuthRequest).auth!.sub;const {productId,productVariantId=null,quantity=1}=req.body;if(typeof productId!=="string"||!Number.isInteger(quantity)||quantity<1)throw new HttpError(400,"productId and a positive integer quantity are required");const product=await prisma.product.findFirst({where:{id:productId,deletedAt:null,status:ProductStatus.ACTIVE},include:{variants:productVariantId?{where:{id:productVariantId}}:false}});if(!product)throw new HttpError(404,"Product not found or unavailable");const variant=productVariantId?product.variants[0]:undefined;if(productVariantId&&!variant)throw new HttpError(400,"Variant does not belong to product");const cart=await userCart(userId);const existing=await prisma.cartItem.findFirst({where:{cartId:cart.id,productId,productVariantId}});const desired=(existing?.quantity??0)+quantity;if((variant?.stock??product.stock??0)<desired)throw new HttpError(409,"Requested quantity exceeds available stock");if(existing)await prisma.cartItem.update({where:{id:existing.id},data:{quantity:desired}});else await prisma.cartItem.create({data:{cartId:cart.id,productId,productVariantId,quantity}});res.status(201).json({data:await userCart(userId)});}catch(e){next(e);}});
cartRouter.put("/items/:itemId",async(req,res,next)=>{try{const userId=(req as AuthRequest).auth!.sub;const quantity=Number(req.body.quantity);if(!Number.isInteger(quantity)||quantity<1)throw new HttpError(400,"quantity must be a positive integer");const item=await prisma.cartItem.findFirst({where:{id:req.params.itemId as string,cart:{userId}},include:{product:true,productVariant:true}});if(!item)throw new HttpError(404,"Cart item not found");if((item.productVariant?.stock??item.product?.stock??0)<quantity)throw new HttpError(409,"Requested quantity exceeds available stock");await prisma.cartItem.update({where:{id:item.id},data:{quantity}});res.json({data:await userCart(userId)});}catch(e){next(e);}});
cartRouter.delete("/items/:itemId",async(req,res,next)=>{try{const userId=(req as AuthRequest).auth!.sub;const item=await prisma.cartItem.findFirst({where:{id:req.params.itemId as string,cart:{userId}},select:{id:true}});if(!item)throw new HttpError(404,"Cart item not found");await prisma.cartItem.delete({where:{id:item.id}});res.status(204).send();}catch(e){next(e);}});
cartRouter.delete("/",async(req,res,next)=>{try{const userId=(req as AuthRequest).auth!.sub;await prisma.cartItem.deleteMany({where:{cart:{userId}}});res.status(204).send();}catch(e){next(e);}});
