import { Router } from "express";
import { forgotPassword, login, register, resetPassword } from "./auth.service.js";
import { requireAuth, type AuthRequest } from "./auth.middleware.js";
import { getUser, updateUser } from "../users/users.service.js";
export const authRouter = Router();
authRouter.post("/register", async (req, res, next) => { try { res.status(201).json({ data: await register(req.body) }); } catch (e) { next(e); } });
authRouter.post("/login", async (req, res, next) => { try { res.json({ data: await login(req.body.email, req.body.password) }); } catch (e) { next(e); } });
authRouter.post("/forgot-password", async (req, res, next) => { try { const { email } = req.body ?? {}; res.json({ data: await forgotPassword(email) }); } catch (e) { next(e); } });
authRouter.post("/reset-password", async (req, res, next) => { try { const { token, password } = req.body ?? {}; res.json({ data: await resetPassword(token, password) }); } catch (e) { next(e); } });
authRouter.get("/me", requireAuth, async (req, res, next) => { try { const auth = (req as AuthRequest).auth; if (!auth?.sub) throw new Error("Authentication required"); const user = await getUser(auth.sub); res.json({ data: user }); } catch (e) { next(e); } });
authRouter.patch("/me", requireAuth, async (req, res, next) => { try { const auth = (req as AuthRequest).auth; if (!auth?.sub) throw new Error("Authentication required"); const body = req.body ?? {}; if (typeof body !== "object" || Array.isArray(body)) throw new Error("Invalid request body");
      const { fullName, email, phone } = body as { fullName?: unknown; email?: unknown; phone?: unknown };
      const updateInput: Record<string, string | null | undefined> = {};
      if (fullName !== undefined) updateInput.fullName = typeof fullName === "string" ? fullName : undefined;
      if (email !== undefined) updateInput.email = typeof email === "string" ? email : undefined;
      if (phone !== undefined) updateInput.phone = typeof phone === "string" ? phone : undefined;
      const user = await updateUser(auth.sub, updateInput);
      res.json({ data: user });
    } catch (e) { next(e); } });
